#!/bin/bash

PWD=`pwd`

nodeDir=$PWD/nodeRed

UDIR=`grep userDir nodeRed/nodeSettings.js`

#echo -e "Original User Directory: $UDIR"
#echo "New Dir:  $nodeDir"


match=`echo $UDIR | cut -d \' -f 2`

echo $UDIR | sed '' "s/$match/${nodeDir}/"
